# # mise config files are hierarchical. mise will find all of the config files
# # in all parent directories and merge them together.
# # You might have a structure like:
#
# * ~/work/project/mise.toml   # a config file for a specific work project
# * ~/work/mise.toml           # a config file for projects related to work
# * ~/.config/mise/config.toml # the global config file
# * /etc/mise/config.toml      # the system config file
#
# # This setup allows you to define default versions and configuration across
# # all projects but override them for specific projects.

[tools]
python = "3.11.5"
ruby = "3.3.4"
node = "22.14.0"
perl = "5.40.0"
dotnet-core = "8.0.303"
php = "8.3.12"
java = "23.0.2"
maven = "3.8.1"
go = "1.24.3"
gradle = "7.5.1"
groovy = "3.0.13"
rust = "1.90.0"
tomcat = "9.0.75"
pipx = "1.6.0"
pnpm = "10.30.1"
lua = "5.4.7"
awscli = "2.17.32"
kubectl = "1.31.0"
spring-boot = "3.3.3"
bun = "1.2.8"
uv = "0.8.12"
usage = "latest"
watchexec = "latest"

[settings]
experimental = true
